=== SvetlanaK367/TrainingJAVA/XML_Parser/out/production/XML_Parser/data/cards.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://www.example.com/OldCards"
        xmlns:tns="http://www.example.com/OldCards" 
        elementFormDefault="qualified">
    <element name="OldCards">
        <complexType>
	    <sequence>
	        <element name="card" type="tns:Card" minOccurs="1" maxOccurs="unbounded" />
            </sequence>
	</complexType>
    </element>
    <complexType name="Card">
        <sequence>
	    <element name="year" type="positiveInteger" />
	    <element name="country" type="string" />
	    <element name="numbers" type="positiveInteger" />
	    <element name="characteristic" type="tns:Characteristic" />
	</sequence>
	<attribute name="registration" type="tns:Id" use="required" />
	<attribute name="author" type="string" use="optional" />
	<attribute name="colored">
	   <simpleType>
        	<restriction base="string">
            	    <enumeration value="yes"></enumeration>
            	    <enumeration value="no"></enumeration>
        	</restriction>
	    </simpleType>
	</attribute>
    </complexType>
    <simpleType name="Id">
        <restriction base="ID">
	    <pattern value="[a-zA-Z]{1}[a-zA-Z0-9_]{5}"/>
	</restriction>
    </simpleType>
    <complexType name="Characteristic">
        <sequence>
	    <element name="valuable" type="string" />
	    <element name="thema" type="string" />
	    <element name="type" type="string" />
	</sequence>
    </complexType>
</schema>

=== SvetlanaK367/TrainingJAVA/XML_Parser/out/production/XML_Parser/data/cards - Copy (2).xml
<?xml version="1.0" encoding="UTF-8"?>
<OldCards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/<OldCards"
          xsi:schemaLocation="http://www.example.com/<OldCards cards.xsd">
<OldCards>
    <card registration="r00001" author="Ivanov" colored="no">
        <year>1891</year>
        <country>Russia</country>
	<numbers>100</numbers>
	<characteristic>
	    <valuable>historical</valuable>
	    <thema>Cityscape</thema>
	    <type>Greeting</type>
	</characteristic>
    </card>
    <card registration="r00002" author="Krishtov" colored="yes">
        <year>1900</year>
        <country>Poland</country>
	<numbers>90</numbers>
	<characteristic>
	    <valuable>thematic</valuable>
	    <thema>Nature</thema>
	    <type>General</type>
	</characteristic>
    </card>
    <card registration="r00003" author="Petrov" colored="no">
        <year>1917</year>
        <country>Russia</country>
	<numbers>120</numbers>
	<characteristic>
	    <valuable>historical</valuable>
	    <thema>People</thema>
	    <type>Advertising</type>
	</characteristic>
    </card>
    <card registration="r00004" author="Sidorov" colored="no">
        <year>1878</year>
        <country>Russia</country>
	<numbers>20</numbers>
	<characteristic>
	    <valuable>collectible</valuable>
	    <thema>Religion</thema>
	    <type>General</type>
	</characteristic>
    </card>
    <card registration="r00005" author="Hipple" colored="yes">
        <year>1955</year>
        <country>USA</country>
	<numbers>300</numbers>
	<characteristic>
	    <valuable>unusual</valuable>
	    <thema>Sport</thema>
	    <type>Advertising</type>
	</characteristic>
    </card>
    <card registration="r00006" author="Greco" colored="no">
        <year>1791</year>
        <country>Greece</country>
	<numbers>50</numbers>
	<characteristic>
	    <valuable>historical</valuable>
	    <thema>Architecture</thema>
	    <type>General</type>
	</characteristic>
    </card>
    <card registration="r00007" author="Savicki" colored="yes">
        <year>1980</year>
        <country>Belarus</country>
	<numbers>300</numbers>
	<characteristic>
	    <valuable>thematic</valuable>
	    <thema>Nature</thema>
	    <type>Greeting</type>
	</characteristic>
    </card>
</OldCards>
